spring:
  datasource:
    url: jdbc:h2:mem:test
    username: su
    password: su
    driverClassName: org.h2.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true